// <auto-generated />
namespace SalemDance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DayOfWeekEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DayOfWeekEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201412020757081_DayOfWeekEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
